### PR TITLE
make gorealisCLient functions handled by client pointer

### PR DESCRIPTION
**Pull request by smothiki**
GorealisClient functions are called using pointer

### CODE REVIEW

**Comment by rdelval** [comment]
-1 on this PR from me.  Since Realis is an interface, it's automatically stored as a pointer under the hood: https://research.swtch.com/interfaces

So this change ends up being cometic only :slightly_smiling_face:

**Comment by smothiki** [comment]
Interface stores a copy of the object value that is assigned, not the value itself. Basically, if the assigned object is not a pointer, it is passed by value. Gorealis focuses on developing a CLI Library and it's up to the user how he will use it to access aurora.  I don't agree with reason that finding bugs will be hard if we implement pointers.  Rather we should do better error handling. Also implementing pointer is not new most of the CLI libraries are implemented this way for example. 

https://github.com/docker/docker/blob/master/client/container_kill.go

**Comment by rdelval** [comment]
What you say is indeed correct but the assigned object to an interface type is only a value if its less than a word in size, otherwise, a pointer to a deep copy of the data is stored instead. This means when an interface is copied, only two words will be copied. 

In any case, upon researching further, and while I still disagree with making Realis objects mutable by changing receivers to pointers, it seems like there's enough precedent on using them in these libraries (such as the one that inspired this gorealis, [go-marathon](https://github.com/gambol99/go-marathon/blob/master/client.go)) that I'm not gonna oppose this PR.

**Comment by kkrishna** [comment]
Reason for **pass by reference** vs **value**:
1.    Actually modify the receiver (“read/write” as opposed to just “read”) .. details [here](https://play.golang.org/p/jRiSDqVTyG)
2.    Peformance: struct is very large and a deep copy is expensive

**Pull request merged**
